services:
  postgres:
    image: postgres:16-alpine
    container_name: ${COMPOSE_PROJECT_NAME:-financial}_postgres
    profiles: ["db"]
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:?Variavel DB_USER obrigatoria}
      POSTGRES_PASSWORD: ${DB_PASSWORD:?Variavel DB_PASSWORD obrigatoria}
      POSTGRES_DB: ${DB_NAME:-financial_db}
      TZ: ${TZ:-America/Sao_Paulo}
      PGTZ: ${TZ:-America/Sao_Paulo}
    #ports:
    #  - "127.0.0.1:${DB_PORT:-5432}:5432"
    volumes:
      - ${PGDATA_PATH:-./pgdata}:/var/lib/postgresql/data
    networks:
      - financial-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:?Variavel DB_USER obrigatoria} -d ${DB_NAME:-financial_db}"]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1024M

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ${COMPOSE_PROJECT_NAME:-financial}_api
    profiles: ["app"]
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
        required: false
    environment:
      NODE_ENV: production
      APP_ENV: ${APP_ENV:-development}
      PORT: ${PORT:-3001}
      TZ: ${TZ:-America/Sao_Paulo}
      DATABASE_URL: ${DATABASE_URL:-postgresql://${DB_USER:?Variavel DB_USER obrigatoria}:${DB_PASSWORD:?Variavel DB_PASSWORD obrigatoria}@${DB_HOST:-financial-postgres}:${DB_PORT:-5432}/${DB_NAME:-financial_db}?schema=public}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: 1d
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS:-http://localhost:3000,http://localhost:3001}
      DISABLE_REGISTRATION: ${DISABLE_REGISTRATION:-false}
    ports:
      - "127.0.0.1:${PORT:-3001}:3001"
    networks:
      - financial-net
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1024M

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_APP_ENV: ${APP_ENV:-development}
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:3001}
        NEXT_PUBLIC_DISABLE_REGISTRATION: ${DISABLE_REGISTRATION:-false}
    container_name: ${COMPOSE_PROJECT_NAME:-financial}_frontend
    profiles: ["app"]
    restart: always
    depends_on:
      - api
    environment:
      NODE_ENV: production
      TZ: ${TZ:-America/Sao_Paulo}
      NEXT_PUBLIC_APP_ENV: ${APP_ENV:-development}
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:3001}
      NEXT_PUBLIC_DISABLE_REGISTRATION: ${DISABLE_REGISTRATION:-false}
    ports:
      - "127.0.0.1:${FRONTEND_PORT:-3000}:3000"
    networks:
      - financial-net
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1024M


networks:
  financial-net:
    driver: bridge
